import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import styles from '@/styles/Home.module.css'

const inter = Inter({ subsets: ['latin'] })

const callAPI = async () => {
  try {
    // grabs questions value from input
    const question = document.querySelector('#question-input').value

    // makes fetch request to backend api
    const res = await fetch('/api/answer', {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json',
        'Access-Control-Allow-Origin': '*',
      },
      body: JSON.stringify({
          query: question,
      }),
    });

    const data = await res.json();
    console.log(data);
  } catch (err) {
    // console.log(err);
  }
}

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />

        <form action="/api/form" method="post">
            <label htmlFor="What is your Grammerhub question">What is your question?</label>
            <input type="text" id="input" name="first" required />

            <button type="submit">Submit</button>
        </form>

      </Head>
     
    </>
  )
}