// install node.js 18.12.1 version
import Head from 'next/head'
import Image from 'next/image'
import Question from '../comps/Question'
import Answer from '../comps/Answer'
import Display from '../comps/Display'
import axios from 'axios'
// import { Inter } from '@next/font/google'
import styles from '@/styles/Home.module.css'
import {useEffect, useState} from 'react'
// import 'boxicons'
const initialState = { answer: '', question: ''}
// const inter = Inter({ subsets: ['latin'] })

const fetchData = async () => {
  const res = await fetch("api/answer", )

  const data = await res.json();
  return data
}

export default function Home() {
  const[answer, setAnswer] = useState(initialState.answer)
  const[question, setQuestion] = useState(initialState.question)
  const[log, setLog] = useState([])
  const[sendQuestion, setSendQuestion] = useState(false)

  function formSubmit(e) {
    e.preventDefault();
    setSendQuestion(true)
  }

  const callAPI = async () => {
    try {
      // makes fetch request to backend api
      const data = await fetchData()
      // console.log(data)
     setAnswer(data.text)
    
      console.log(answer)

    } catch (err) {
      console.log(err);
    }
  }
  useEffect(()=>{
    if (sendQuestion) {
      callAPI();
      setSendQuestion(false)
    }

  }, [sendQuestion])

  useEffect(()=>{ 
    if (answer) {
      setLog ([...log, {question: question, answer: answer}])
      setAnswer(initialState.answer)
      setQuestion(initialState.question)
    }
  }, [answer])

  
  return (
    <>
      <Head>
        <title>Grammerhub</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
    
      <div className='nav_bar'>
            <img src="./images/grammerhub.png"></img>

            <div className='pages'>
                <ul>home</ul>
                <ul>find talent</ul>
                <ul>about</ul>
                <ul>join</ul>
            </div>
      </div>
      
      <Display style={styles} log={log}/>

      
      <section className={styles.form_container}>
        <form className={styles.question_form} onSubmit={formSubmit}>
        <label htmlFor="question-input">Ask grammerhub a question:</label>
          <input id="question-input" className={styles.question_input} type="text" value={question} onChange={(e)=> setQuestion (e.target.value)}></input>
        </form>
      </section>
      <footer>
        <section>
         
        </section>
            <div className='footer_title'>g r a m m e r h u b</div>
            <div className='footer_info'>KEEP IN TOUCH</div>

            <div className='follow_us'>Follow us at:
            <box-icon type='logo' name='facebook'></box-icon>
            <box-icon type='logo' name='discord-alt'></box-icon>
            <box-icon name='linkedin' type='logo' ></box-icon>
            </div>

            <div className='acknowledgements'>
                <p>Built by: Zephyr, Lia, Branden, & Andrea</p>
            </div>
      </footer>
    </>
  )
}

