// install node.js 18.12.1 version
import Head from 'next/head'
import Image from 'next/image'
import Question from '../comps/Question'
import Answer from '../comps/Answer'
import Display from '../comps/Display'
import { Inter } from '@next/font/google'
import styles from '@/styles/Home.module.css'
import {useEffect, useState} from 'react'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  // const[answer, setAnswer] = useState('')
  const[questions, setQuestions] = useState([])
  const[answers, setAnswers] = useState([])

  function formSubmit(e) {
    e.preventDefault();
    callAPI();
  }

  const callAPI = async () => {
    try {

      // grabs questions value from input
      const question = document.querySelector('#question-input').value

      // makes fetch request to backend api
      const res = await fetch('/api/answer', {
        method: 'POST',
        headers: {
          'Content-Type': 'application/json',
          'Access-Control-Allow-Origin': '*',
        },
        body: JSON.stringify({
            query: question,
        }),
      });

      const answer = await res.json();
      setQuestions([...questions, question])

      // setQuestions([...questions, question])
      // setAnswers([...answers, answer])

      // console.log([...questions, question])

    } catch (err) {
      console.log(err);
    }
  }
  
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      
      <Display style={styles} questions={questions} answer="Zephyr"/>
      <section className={styles.form_container}>
        <form className={styles.question_form} onSubmit={formSubmit}>
          <input id="question-input" className={styles.question_input} type="text"></input>
        </form>
      </section>
    </>
  )
}
